### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by AlexNmSED** [wisdomikezogwo/MMAE_Pathology#3]
Thanks for sharing your code, it inspired me a lot.
I want to know what is the total pre-training time for 4 GPUs.

**Comment by wisdomikezogwo** [comment]
Hi, so it depends really on a bunch of training parameters some of which include the masking_ratio/#visible patches and the batch_size, however to give a rough estimate we typically trained our max #visible_patches for about 3-4 days to converge on 4 GPUs with 8gb and even faster on 4GPUs with 16gb each.

**Comment by AlexNmSED** [comment]
thanks for your help. I will try it.
